-- Preserve V1/V2 history. Convert the existing synthetic UUID fixtures to short numeric IDs.
-- Unexpected non-demo UUID data aborts the transaction and requires an explicit mapping.
CREATE FUNCTION pg_temp.demo_id_to_bigint(value UUID) RETURNS BIGINT
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE suffix BIGINT; result BIGINT;
BEGIN
    IF value::text !~ '^[1-5]0000000-0000-0000-0000-[0-9]{12}$' THEN
        RAISE EXCEPTION 'Cannot automatically map non-demo UUID %. Provide an explicit mapping before V3.', value;
    END IF;
    suffix := right(value::text, 12)::BIGINT;
    result := CASE WHEN suffix < 100 THEN suffix ELSE suffix % 100 END;
    IF result < 1 THEN RAISE EXCEPTION 'Unsupported demo ID %', value; END IF;
    RETURN result;
END;
$$;

CREATE TEMP TABLE numeric_id_constraints ON COMMIT DROP AS
SELECT c.conname, c.conrelid::regclass::text AS table_name, pg_get_constraintdef(c.oid) AS definition
FROM pg_constraint c
JOIN pg_class t ON t.oid = c.conrelid
JOIN pg_namespace n ON n.oid = t.relnamespace
WHERE n.nspname = 'public' AND c.contype IN ('f','x');

DO $$
DECLARE col RECORD; constraint_row RECORD; checked_count BIGINT; next_id BIGINT;
BEGIN
    -- Preflight every UUID entity/reference column before changing the schema.
    FOR col IN SELECT table_name, column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND data_type = 'uuid' AND column_name <> 'hold_token'
    LOOP
        EXECUTE format('SELECT count(pg_temp.demo_id_to_bigint(%I)) FROM public.%I',
                       col.column_name, col.table_name) INTO checked_count;
    END LOOP;
    FOR constraint_row IN SELECT * FROM numeric_id_constraints LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', constraint_row.table_name, constraint_row.conname);
    END LOOP;
    FOR col IN SELECT table_name, column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND data_type = 'uuid' AND column_name <> 'hold_token'
        ORDER BY table_name, ordinal_position
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP DEFAULT', col.table_name, col.column_name);
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I TYPE BIGINT USING pg_temp.demo_id_to_bigint(%I)',
                       col.table_name, col.column_name, col.column_name);
        -- Inherited profiles share users.id; they must not allocate a different ID.
        IF col.column_name = 'id' AND col.table_name NOT IN ('admins','customers','staffs') THEN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                           col.table_name);
            EXECUTE format('SELECT coalesce(max(id), 0) + 1 FROM public.%I', col.table_name) INTO next_id;
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id RESTART WITH %s', col.table_name, next_id);
        END IF;
    END LOOP;
    FOR constraint_row IN SELECT * FROM numeric_id_constraints LOOP
        EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s',
                       constraint_row.table_name, constraint_row.conname, constraint_row.definition);
    END LOOP;
END;
$$;

CREATE FUNCTION pg_temp.rewrite_demo_json_ids(value JSONB) RETURNS JSONB
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE payload TEXT := value::TEXT; match TEXT[];
BEGIN
    FOR match IN SELECT regexp_matches(payload, '[1-5]0000000-0000-0000-0000-[0-9]{12}', 'g') LOOP
        payload := replace(payload, match[1], pg_temp.demo_id_to_bigint(match[1]::UUID)::TEXT);
    END LOOP;
    RETURN payload::JSONB;
END;
$$;

DO $$
DECLARE col RECORD;
BEGIN
    FOR col IN SELECT table_name, column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND data_type = 'jsonb'
    LOOP
        EXECUTE format('UPDATE public.%I SET %I = pg_temp.rewrite_demo_json_ids(%I) '
                       'WHERE %I::text ~ %L', col.table_name, col.column_name, col.column_name,
                       col.column_name, '[1-5]0000000-0000-0000-0000-[0-9]{12}');
    END LOOP;
END;
$$;
-- hold_token remains an opaque random token; it is not an entity ID.
